### PR TITLE
#53: Don't allow bots to export

### PR DESCRIPTION
**Pull request by Sam-per**
- Adds a check in the exportToFile method for whether the user is a bot

Previously, the exportToFile command could only be called by a reader or admin. Now the command can only be called by a reader or admin **who is not a bot**

This uses discord's isBot flag (the blue "BOT" tag)

### CODE REVIEW

**Comment by Sam-per** [comment]
resolves #53

**Comment by alopezlago** [comment]
We'll want to add this to a few other commands (newer export commands coming in), so it'd be nice if it could be an method attribute, specifically a PreconditionFilter. I have an unpublished branch that does this. The class looks like:

 [AttributeUsage(AttributeTargets.Method)]
    public class HumanOnlyAttribute : PreconditionAttribute
    {
        [SuppressMessage(
            "Design",
            "CA1062:Validate arguments of public methods",
            Justification = "Discord.Net will pass in non-null CommandContext")]
        public override Task<PreconditionResult> CheckPermissionsAsync(
            ICommandContext context, CommandInfo command, IServiceProvider services)
        {
            if (context.User.IsBot)
            {
                return Task.FromResult(PreconditionResult.FromError("Bots are not allowed to run this command."));
            }

            return Task.FromResult(PreconditionResult.FromSuccess());
        }
    }

**Comment by Sam-per** [comment]
Assuming that your changes are already near completion, it might be more beneficial to close/reject this PR and add the attribute to the appropriate method with your changes.

Alternatively, I could change this PR to incorporate your attribute? Up to you

**Comment by alopezlago** [comment]
I can split out what I have in the next couple days and send out a PR

**Comment by alopezlago** [comment]
See #64

**Comment by Sam-per** [comment]
Assuming that none of the code here is needed and this PR is unnecessary, it can be closed

**Pull request closed without merging**
